### ISSUE TITLE
You can't see real-time comments on the live broadcast UI, nor can you post real-time comments.

### ISSUE THREAD

**Issue by tkp206093** [sepehrkiller/FixYoutubeUI#4]
When watching a live video, the chat box may disappear, which prevents viewing real-time comments and engaging in live interactions.

**Comment by sepehrkiller** [comment]
why did you close this issue? 
did you manage to resolve the issue and if so, how? 
was the issue caused by this filter list?

**Comment by tkp206093** [comment]
Yes, I resolved the issue. Sorry, this issue pertains to a different filter list.

**Comment by sepehrkiller** [comment]
No problem, glad that you've solved it and it wasn't caused by this
may i perhaps know which filter list was causing the issue?

**Comment by tkp206093** [comment]
https://[gist.githubusercontent.com/aggarwalsushant/9461f3b09d6a08c9f03f74071a066996/raw/536886701dddb4c08edbbbfea2cadcadddb00064/ublockStaticCustomFilters.txt](https://gist.githubusercontent.com/aggarwalsushant/9461f3b09d6a08c9f03f74071a066996/raw/536886701dddb4c08edbbbfea2cadcadddb00064/ublockStaticCustomFilters.txt)

**Comment by sepehrkiller** [comment]
Thank you, have a good one
